controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    miniv_control:
      type: miniv_control/MiniVHardware

miniv_control:
  ros__parameters:
    joints:
      - left_azimuth_link
      - right_azimuth_link